workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
